FROM python:3.6.7-slim
MAINTAINER seongwonhan88@gmail.com

# settings module change to production, language from ascii to utf-8
ENV LANG=C.UTF-8

#package upgrade
RUN apt-get -y update
RUN apt-get -y dist-upgrade
RUN apt-get -y install gcc nginx supervisor
RUN pip3 install uwsgi

# copy requirements
# if requirements has not changed, pip3 will not install
COPY requirements_production.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt